### ISSUE TITLE
Refactor creation of CTrees from files

### ISSUE THREAD

**Issue by petermr** [ContentMine/norma#37] opened 2016-05-07 23:09 UTC
Current method of creating CTrees assumes that files that are children of project (or possibly CTree) are to be transformed to directories. This is fragile and unpredictable. Change to use specialist command.

**Comment by tarrow** [comment] 2016-05-09 08:51
I this is a duplicate of #39 and written in more detail there so I'll close.

**Closed by tarrow** 2016-05-09 08:51 UTC
